### ISSUE TITLE
not working in bitwig studio.

### ISSUE THREAD

**Issue by perol-d** [Kiriki-liszt/JS_Inflator#34] opened 2024-06-29 21:45 UTC
tested on 2 different windows systems.
tried to fully delete this file thats on error message, not fixed.
![image](https://github.com/Kiriki-liszt/JS_Inflator/assets/174215812/ba1e71c2-93c3-4a95-8bc2-b03346ed44ea)

**Comment by Kiriki-liszt** [comment] 2024-06-30 03:38
Hello!
Thanks for checking this plugin out and reporting!
A similar issue was reported and fixed in v2.0.2.1 : https://github.com/Kiriki-liszt/JS_Inflator/issues/33
Which version did this happened, in v2.0.2 or v2.0.2.1?
That would help this issue =)

Have a nice day!

**Comment by perol-d** [comment] 2024-06-30 11:55
hello!
it happens on both versions, only in bitwig.
i used old version about 0.5 year ago and it was running correctly.

**Comment by Kiriki-liszt** [comment] 2024-06-30 17:12
Oh, now that need a fix!!
I was unable to reproduce the error, but I have some suspicious parts for that error msg.
Here's a beta version of this bug fix, so you could try and comment if error is resolved or not!
If the error is still there, please comment more how to reproduce that bug =)
[JS Inflator Win v2.0.2.2.zip](https://github.com/user-attachments/files/16045505/JS.Inflator.Win.v2.0.2.2.zip)

Have a nice day!

**Comment by perol-d** [comment] 2024-07-02 00:46
YES it WORKS! thank you! <3

**Comment by Kiriki-liszt** [comment] 2024-07-04 18:42
Hello again!
I updated the official release to v2.0.2.2, and I would appreciate final check of this error before I close this issue. 
Did the error fixed in the official latest release, too?
Hope it does =)

Have a great day!

**Comment by perol-d** [comment] 2024-07-05 17:47
hello
yes, its fixed, thank you again!

**Closed as completed** 2024-07-06 02:57 UTC
